// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolleyballFinal.Models;

#nullable disable

namespace VolleyballFinal.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20231119052848_SeedOlympicPlayersData")]
    partial class SeedOlympicPlayersData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VolleyballFinal.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = "27",
                            Height = "175cm",
                            Number = 1,
                            PlayerName = "Matias Sanchez",
                            Position = "Setter",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Age = "35",
                            Height = "200cm",
                            Number = 2,
                            PlayerName = "Federico Pereyra",
                            Position = "Opposite Hitter",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 3,
                            Age = "34",
                            Height = "195cm",
                            Number = 6,
                            PlayerName = "Cristian Poglajen",
                            Position = "Outside Hitter",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 4,
                            Age = "34",
                            Height = "197cm",
                            Number = 7,
                            PlayerName = "Facundo Conte",
                            Position = "Outside Hitter",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 5,
                            Age = "26",
                            Height = "198cm",
                            Number = 8,
                            PlayerName = "Agustin Loser",
                            Position = "Middle Blocker",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 6,
                            Age = "27",
                            Height = "176cm",
                            Number = 9,
                            PlayerName = "Santiago Danani",
                            Position = "Libero",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 7,
                            Age = "32",
                            Height = "200cm",
                            Number = 11,
                            PlayerName = "Sebastian Sole",
                            Position = "Middle Blocker",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Age = "27",
                            Height = "198cm",
                            Number = 12,
                            PlayerName = "Bruno Lima",
                            Position = "Opposite Hitter",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 9,
                            Age = "31",
                            Height = "198cm",
                            Number = 13,
                            PlayerName = "Ezequiel Palacios",
                            Position = "Outside Hitter",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 10,
                            Age = "35",
                            Height = "191cm",
                            Number = 15,
                            PlayerName = "Luciano De Cecco",
                            Position = "Setter",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            Age = "31",
                            Height = "191cm",
                            Number = 17,
                            PlayerName = "Nicolas Mendez",
                            Position = "Outside Hitter",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Age = "32",
                            Height = "197cm",
                            Number = 18,
                            PlayerName = "Martin Ramos",
                            Position = "Middle Blocker",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 13,
                            Age = "37",
                            Height = "190cm",
                            Number = 1,
                            PlayerName = "Bruno Mossa Rezende",
                            Position = "Setter",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 14,
                            Age = "34",
                            Height = "199cm",
                            Number = 5,
                            PlayerName = "Maurício Borges Almeida Silva",
                            Position = "Outside Hitter",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 15,
                            Age = "27",
                            Height = "186cm",
                            Number = 6,
                            PlayerName = "Fernando Gil Kreling",
                            Position = "Setter",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 16,
                            Age = "36",
                            Height = "198cm",
                            Number = 8,
                            PlayerName = "Wallace De Souza",
                            Position = "Opposite Hitter",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 17,
                            Age = "35",
                            Height = "202cm",
                            Number = 9,
                            PlayerName = "Yoandy Leal Hidalgo",
                            Position = "Outside Hitter",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 18,
                            Age = "32",
                            Height = "208cm",
                            Number = 12,
                            PlayerName = "Isac Santos",
                            Position = "Middle Blocker",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 19,
                            Age = "35",
                            Height = "207cm",
                            Number = 13,
                            PlayerName = "Mauricio Luiz De Souza",
                            Position = "Middle Blocker",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 20,
                            Age = "28",
                            Height = "199cm",
                            Number = 14,
                            PlayerName = "Douglas Correia De Souza",
                            Position = "Outside Hitter",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 21,
                            Age = "37",
                            Height = "209cm",
                            Number = 16,
                            PlayerName = "Lucas Saatkamp",
                            Position = "Middle Blocker",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 22,
                            Age = "34",
                            Height = "190cm",
                            Number = 17,
                            PlayerName = "Thales Hoss",
                            Position = "Libero",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 23,
                            Age = "31",
                            Height = "196cm",
                            Number = 18,
                            PlayerName = "Ricardo Lucarelli Souza",
                            Position = "Outside Hitter",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 24,
                            Age = "29",
                            Height = "202cm",
                            Number = 21,
                            PlayerName = "Alan Souza",
                            Position = "Opposite Hitter",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Age = "31",
                            Height = "191cm",
                            Number = 1,
                            PlayerName = "Tyler Sanders",
                            Position = "Setter",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 26,
                            Age = "34",
                            Height = "201cm",
                            Number = 2,
                            PlayerName = "Tyler Gordon Perrin",
                            Position = "Outside Hitter",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 27,
                            Age = "33",
                            Height = "191cm",
                            Number = 3,
                            PlayerName = "Steven Marshall",
                            Position = "Libero",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 28,
                            Age = "31",
                            Height = "200cm",
                            Number = 4,
                            PlayerName = "Nicholas Hoag",
                            Position = "Outside Hitter",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 29,
                            Age = "28",
                            Height = "201cm",
                            Number = 7,
                            PlayerName = "Stephen Timothy Maar",
                            Position = "Outside Hitter",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 30,
                            Age = "34",
                            Height = "194cm",
                            Number = 9,
                            PlayerName = "Jay Blankenau",
                            Position = "Setter",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 31,
                            Age = "29",
                            Height = "200cm",
                            Number = 10,
                            PlayerName = "Ryan Joseph Sclater",
                            Position = "Opposite Hitter",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 32,
                            Age = "31",
                            Height = "210cm",
                            Number = 12,
                            PlayerName = "Lucas Van Berkel",
                            Position = "Middle Blocker",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            Age = "25",
                            Height = "206cm",
                            Number = 13,
                            PlayerName = "Sharone Vernon-Evans",
                            Position = "Opposite Hitter",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 34,
                            Age = "34",
                            Height = "205cm",
                            Number = 17,
                            PlayerName = "Graham Vigrass",
                            Position = "Middle Blocker",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 35,
                            Age = "35",
                            Height = "184cm",
                            Number = 19,
                            PlayerName = "Blair Cameron Bann",
                            Position = "Libero",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 36,
                            Age = "28",
                            Height = "209cm",
                            Number = 20,
                            PlayerName = "Arthur Szwarc",
                            Position = "Opposite Hitter",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 37,
                            Age = "25",
                            Height = "204cm",
                            Number = 1,
                            PlayerName = "Barthélémy Chinenyeze",
                            Position = "Middle Blocker",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 38,
                            Age = "33",
                            Height = "188cm",
                            Number = 2,
                            PlayerName = "Jenia Grebennikov",
                            Position = "Libero",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 39,
                            Age = "26",
                            Height = "207cm",
                            Number = 4,
                            PlayerName = "Jean Patry",
                            Position = "Opposite Hitter",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 40,
                            Age = "34",
                            Height = "183cm",
                            Number = 6,
                            PlayerName = "Benjamin Toniutti",
                            Position = "Setter",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 41,
                            Age = "33",
                            Height = "200cm",
                            Number = 7,
                            PlayerName = "Kevin Tillie",
                            Position = "Outside Hitter",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 42,
                            Age = "32",
                            Height = "194cm",
                            Number = 9,
                            PlayerName = "Earvin Ngapeth",
                            Position = "Outside Hitter",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 43,
                            Age = "29",
                            Height = "196cm",
                            Number = 11,
                            PlayerName = "Antoine Brizard",
                            Position = "Setter",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 44,
                            Age = "27",
                            Height = "196cm",
                            Number = 12,
                            PlayerName = "Stephen Boyer",
                            Position = "Opposite Hitter",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 45,
                            Age = "31",
                            Height = "206cm",
                            Number = 14,
                            PlayerName = "Nicolas Le Goff",
                            Position = "Middle Blocker",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 46,
                            Age = "27",
                            Height = "197cm",
                            Number = 16,
                            PlayerName = "Daryl Bultor",
                            Position = "Middle Blocker",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 47,
                            Age = "29",
                            Height = "199cm",
                            Number = 17,
                            PlayerName = "Trevor Clevenot",
                            Position = "Outside Hitter",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 48,
                            Age = "31",
                            Height = "198cm",
                            Number = 19,
                            PlayerName = "Yacine Louati",
                            Position = "Outside Hitter",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 49,
                            Age = "30",
                            Height = "196cm",
                            Number = 2,
                            PlayerName = "Milad Ebadipour Ghara H.",
                            Position = "Outside Hitter",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 50,
                            Age = "38",
                            Height = "189cm",
                            Number = 4,
                            PlayerName = "Mir Saeid Marouflakrani",
                            Position = "Setter",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 51,
                            Age = "36",
                            Height = "203cm",
                            Number = 6,
                            PlayerName = "Seyed Mohammad Mousavi Eraghi",
                            Position = "Middle Blocker",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 52,
                            Age = "33",
                            Height = "204cm",
                            Number = 9,
                            PlayerName = "Masoud Gholami",
                            Position = "Middle Blocker",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 53,
                            Age = "32",
                            Height = "202cm",
                            Number = 10,
                            PlayerName = "Amir Ghafour",
                            Position = "Opposite Hitter",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 54,
                            Age = "24",
                            Height = "205cm",
                            Number = 11,
                            PlayerName = "Saber Kazemi",
                            Position = "Opposite Hitter",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 55,
                            Age = "24",
                            Height = "193cm",
                            Number = 12,
                            PlayerName = "Morteza Sharifi",
                            Position = "Outside Hitter",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 56,
                            Age = "26",
                            Height = "205cm",
                            Number = 15,
                            PlayerName = "Aliasghar Mojarad",
                            Position = "Middle Blocker",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 57,
                            Age = "24",
                            Height = "198cm",
                            Number = 17,
                            PlayerName = "Meisam Salehi",
                            Position = "Outside Hitter",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 58,
                            Age = "37",
                            Height = "172cm",
                            Number = 19,
                            PlayerName = "Mahdi Marandi",
                            Position = "Libero",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 59,
                            Age = "31",
                            Height = "180cm",
                            Number = 21,
                            PlayerName = "Arman Salehi",
                            Position = "Libero",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 60,
                            Age = "25",
                            Height = "204cm",
                            Number = 24,
                            PlayerName = "Javad Karimisouchelmaei",
                            Position = "Setter",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 61,
                            Age = "34",
                            Height = "202cm",
                            Number = 2,
                            PlayerName = "Jiri Kovar",
                            Position = "Outside Hitter",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 62,
                            Age = "32",
                            Height = "200cm",
                            Number = 4,
                            PlayerName = "Luca Vettori",
                            Position = "Opposite Hitter",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 63,
                            Age = "38",
                            Height = "200cm",
                            Number = 5,
                            PlayerName = "Osmany Juantorena",
                            Position = "Outside Hitter",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 64,
                            Age = "27",
                            Height = "200cm",
                            Number = 6,
                            PlayerName = "Simone Giannelli",
                            Position = "Setter",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 65,
                            Age = "35",
                            Height = "204cm",
                            Number = 9,
                            PlayerName = "Ivan Zaytsev",
                            Position = "Outside Hitter",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 66,
                            Age = "33",
                            Height = "208cm",
                            Number = 11,
                            PlayerName = "Matteo Piano",
                            Position = "Middle Blocker",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 67,
                            Age = "38",
                            Height = "180cm",
                            Number = 13,
                            PlayerName = "Massimo Colaci",
                            Position = "Libero",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 68,
                            Age = "26",
                            Height = "201cm",
                            Number = 14,
                            PlayerName = "Gianluca Galassi",
                            Position = "Middle Blocker",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 69,
                            Age = "25",
                            Height = "188cm",
                            Number = 15,
                            PlayerName = "Riccardo Sbertoli",
                            Position = "Setter",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 70,
                            Age = "31",
                            Height = "204cm",
                            Number = 17,
                            PlayerName = "Simone Anzani",
                            Position = "Middle Blocker",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 71,
                            Age = "21",
                            Height = "205cm",
                            Number = 18,
                            PlayerName = "Alessandro Michieletto",
                            Position = "Outside Hitter",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 72,
                            Age = "24",
                            Height = "200cm",
                            Number = 19,
                            PlayerName = "Daniele Lavia",
                            Position = "Outside Hitter",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 73,
                            Age = "37",
                            Height = "193cm",
                            Number = 1,
                            PlayerName = "Kunihiro Shimizu",
                            Position = "Opposite Hitter",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 74,
                            Age = "27",
                            Height = "200cm",
                            Number = 2,
                            PlayerName = "Taishi Onodera",
                            Position = "Middle Blocker",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 75,
                            Age = "31",
                            Height = "183cm",
                            Number = 3,
                            PlayerName = "Naonobu Fujii",
                            Position = "Setter",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 76,
                            Age = "29",
                            Height = "204cm",
                            Number = 6,
                            PlayerName = "Akihiro Yamauchi",
                            Position = "Middle Blocker",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 77,
                            Age = "23",
                            Height = "187cm",
                            Number = 11,
                            PlayerName = "Yuji Nishida",
                            Position = "Opposite Hitter",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 78,
                            Age = "29",
                            Height = "175cm",
                            Number = 12,
                            PlayerName = "Masahiro Sekita",
                            Position = "Setter",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 79,
                            Age = "27",
                            Height = "191cm",
                            Number = 14,
                            PlayerName = "Yuki Ishikawa",
                            Position = "Outside Hitter",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 80,
                            Age = "32",
                            Height = "193cm",
                            Number = 15,
                            PlayerName = "Haku Ri",
                            Position = "Middle Blocker",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 81,
                            Age = "26",
                            Height = "190cm",
                            Number = 17,
                            PlayerName = "Kenta Takanashi",
                            Position = "Outside Hitter",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 82,
                            Age = "22",
                            Height = "194cm",
                            Number = 19,
                            PlayerName = "Tatsunori Otsuka",
                            Position = "Outside Hitter",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 83,
                            Age = "28",
                            Height = "171cm",
                            Number = 20,
                            PlayerName = "Tomohiro Yamamoto",
                            Position = "Libero",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 84,
                            Age = "22",
                            Height = "188cm",
                            Number = 21,
                            PlayerName = "Ran Takahashi",
                            Position = "Outside Hitter",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 85,
                            Age = "35",
                            Height = "205cm",
                            Number = 1,
                            PlayerName = "Piotr Nowakowski",
                            Position = "Middle Blocker",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 86,
                            Age = "29",
                            Height = "204cm",
                            Number = 5,
                            PlayerName = "Lukasz Kaczmarek",
                            Position = "Opposite Hitter",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 87,
                            Age = "35",
                            Height = "205cm",
                            Number = 6,
                            PlayerName = "Bartosz Kurek",
                            Position = "Opposite Hitter",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 88,
                            Age = "30",
                            Height = "202cm",
                            Number = 9,
                            PlayerName = "Wilfredo Leon Venero",
                            Position = "Outside Hitter",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 89,
                            Age = "33",
                            Height = "196cm",
                            Number = 11,
                            PlayerName = "Fabian Drzyzga",
                            Position = "Setter",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 90,
                            Age = "36",
                            Height = "187cm",
                            Number = 12,
                            PlayerName = "Grzegorz Lomacz",
                            Position = "Setter",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 91,
                            Age = "35",
                            Height = "191cm",
                            Number = 13,
                            PlayerName = "Michal Kubiak",
                            Position = "Outside Hitter",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 92,
                            Age = "28",
                            Height = "196cm",
                            Number = 14,
                            PlayerName = "Aleksander Sliwka",
                            Position = "Outside Hitter",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 93,
                            Age = "26",
                            Height = "199cm",
                            Number = 15,
                            PlayerName = "Jakub Kochanowski",
                            Position = "Middle Blocker",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 94,
                            Age = "27",
                            Height = "195cm",
                            Number = 16,
                            PlayerName = "Kamil Semeniuk",
                            Position = "Outside Hitter",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 95,
                            Age = "33",
                            Height = "184cm",
                            Number = 17,
                            PlayerName = "Pawel Zatorski",
                            Position = "Libero",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 96,
                            Age = "29",
                            Height = "210cm",
                            Number = 20,
                            PlayerName = "Mateusz Bieniek",
                            Position = "Middle Blocker",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 97,
                            Age = "29",
                            Height = "198cm",
                            Number = 1,
                            PlayerName = "Yaroslav Podlesnykh",
                            Position = "Outside Hitter",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 98,
                            Age = "33",
                            Height = "208cm",
                            Number = 4,
                            PlayerName = "Artem Volvich",
                            Position = "Middle Blocker",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 99,
                            Age = "28",
                            Height = "201cm",
                            Number = 7,
                            PlayerName = "Dmitry Volkov",
                            Position = "Outside Hitter",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 100,
                            Age = "28",
                            Height = "207cm",
                            Number = 9,
                            PlayerName = "Ivan Iakovlev",
                            Position = "Middle Blocker",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 101,
                            Age = "27",
                            Height = "200cm",
                            Number = 10,
                            PlayerName = "Denis Bogdan",
                            Position = "Outside Hitter",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 102,
                            Age = "28",
                            Height = "198cm",
                            Number = 11,
                            PlayerName = "Pavel Pankov",
                            Position = "Setter",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 103,
                            Age = "28",
                            Height = "197cm",
                            Number = 15,
                            PlayerName = "Victor Poletaev",
                            Position = "Opposite Hitter",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 104,
                            Age = "35",
                            Height = "202cm",
                            Number = 17,
                            PlayerName = "Maxim Mikhaylov",
                            Position = "Opposite Hitter",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 105,
                            Age = "28",
                            Height = "209cm",
                            Number = 18,
                            PlayerName = "Egor Kliuka",
                            Position = "Outside Hitter",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 106,
                            Age = "29",
                            Height = "207cm",
                            Number = 20,
                            PlayerName = "Ilyas Kurkaev",
                            Position = "Middle Blocker",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 107,
                            Age = "32",
                            Height = "198cm",
                            Number = 24,
                            PlayerName = "Igor Kobzar",
                            Position = "Setter",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 108,
                            Age = "31",
                            Height = "190cm",
                            Number = 27,
                            PlayerName = "Valentin Golubev",
                            Position = "Libero",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 109,
                            Age = "34",
                            Height = "199cm",
                            Number = 2,
                            PlayerName = "Ahmed Kadhi",
                            Position = "Middle Blocker",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 110,
                            Age = "28",
                            Height = "193cm",
                            Number = 3,
                            PlayerName = "Khaled Ben Slimene",
                            Position = "Setter",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 111,
                            Age = "32",
                            Height = "188cm",
                            Number = 6,
                            PlayerName = "Mohamed Ali Ben Othmen",
                            Position = "Outside Hitter",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 112,
                            Age = "34",
                            Height = "198cm",
                            Number = 7,
                            PlayerName = "Elyes Karamosli",
                            Position = "Outside Hitter",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 113,
                            Age = "31",
                            Height = "205cm",
                            Number = 9,
                            PlayerName = "Omar Agrebi",
                            Position = "Middle Blocker",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 114,
                            Age = "33",
                            Height = "191cm",
                            Number = 10,
                            PlayerName = "Hamza Nagga",
                            Position = "Opposite Hitter",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 115,
                            Age = "33",
                            Height = "195cm",
                            Number = 11,
                            PlayerName = "Ismail Moalla",
                            Position = "Outside Hitter",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 116,
                            Age = "44",
                            Height = "184cm",
                            Number = 12,
                            PlayerName = "Mehdi Ben Cheikh",
                            Position = "Setter",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 117,
                            Age = "27",
                            Height = "198cm",
                            Number = 13,
                            PlayerName = "Selim Mbareki",
                            Position = "Middle Blocker",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 118,
                            Age = "27",
                            Height = "199cm",
                            Number = 15,
                            PlayerName = "Wassim Ben Tara",
                            Position = "Opposite Hitter",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 119,
                            Age = "22",
                            Height = "188cm",
                            Number = 19,
                            PlayerName = "Aymen Bouguerra",
                            Position = "Outside Hitter",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 120,
                            Age = "32",
                            Height = "186cm",
                            Number = 20,
                            PlayerName = "Saddem Hmissi",
                            Position = "Libero",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 121,
                            Age = "36",
                            Height = "202cm",
                            Number = 1,
                            PlayerName = "Matthew Anderson",
                            Position = "Opposite Hitter",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 122,
                            Age = "31",
                            Height = "196cm",
                            Number = 3,
                            PlayerName = "Taylor Sander",
                            Position = "Outside Hitter",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 123,
                            Age = "26",
                            Height = "201cm",
                            Number = 5,
                            PlayerName = "Kyle Ensing",
                            Position = "Opposite Hitter",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 124,
                            Age = "29",
                            Height = "203cm",
                            Number = 6,
                            PlayerName = "Mitchell Stahl",
                            Position = "Middle Blocker",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 125,
                            Age = "35",
                            Height = "190cm",
                            Number = 7,
                            PlayerName = "Kawika Shoji",
                            Position = "Setter",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 126,
                            Age = "26",
                            Height = "198cm",
                            Number = 8,
                            PlayerName = "Torey Defalco",
                            Position = "Outside Hitter",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 127,
                            Age = "30",
                            Height = "198cm",
                            Number = 11,
                            PlayerName = "Micah Christenson",
                            Position = "Setter",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 128,
                            Age = "36",
                            Height = "205cm",
                            Number = 12,
                            PlayerName = "Maxwell Holt",
                            Position = "Middle Blocker",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 129,
                            Age = "30",
                            Height = "198cm",
                            Number = 17,
                            PlayerName = "Thomas Jaeschke",
                            Position = "Outside Hitter",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 130,
                            Age = "35",
                            Height = "205cm",
                            Number = 18,
                            PlayerName = "Garrett Muagututia",
                            Position = "Outside Hitter",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 131,
                            Age = "38",
                            Height = "201cm",
                            Number = 20,
                            PlayerName = "David Smith",
                            Position = "Middle Blocker",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 132,
                            Age = "34",
                            Height = "184cm",
                            Number = 22,
                            PlayerName = "Erik Shoji",
                            Position = "Libero",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 133,
                            Age = "35",
                            Height = "185cm",
                            Number = 1,
                            PlayerName = "Armando Fernando Velasquez Escalante",
                            Position = "Setter",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 134,
                            Age = "34",
                            Height = "194cm",
                            Number = 3,
                            PlayerName = "Fernando Gonzalez",
                            Position = "Outside Hitter",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 135,
                            Age = "32",
                            Height = "179cm",
                            Number = 4,
                            PlayerName = "Héctor Mata",
                            Position = "Libero",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 136,
                            Age = "30",
                            Height = "204cm",
                            Number = 5,
                            PlayerName = "Emerson Alexander Rodriguez Gonzalez",
                            Position = "Opposite Hitter",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 137,
                            Age = "39",
                            Height = "200cm",
                            Number = 6,
                            PlayerName = "Robert Manuel Oramas Brizuela",
                            Position = "Middle Blocker",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 138,
                            Age = "35",
                            Height = "200cm",
                            Number = 7,
                            PlayerName = "Edson Alberto Valencia Gonzalez",
                            Position = "Middle Blocker",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 139,
                            Age = "34",
                            Height = "192cm",
                            Number = 9,
                            PlayerName = "Jose Manuel Carrasco Angulo",
                            Position = "Setter",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 140,
                            Age = "33",
                            Height = "196cm",
                            Number = 11,
                            PlayerName = "José Verdi",
                            Position = "Middle Blocker",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 141,
                            Age = "25",
                            Height = "196cm",
                            Number = 14,
                            PlayerName = "Eliecer Alfonso Canelo Sanchez",
                            Position = "Outside Hitter",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 142,
                            Age = "34",
                            Height = "196cm",
                            Number = 15,
                            PlayerName = "Luis Antonio Arias Guzman",
                            Position = "Opposite Hitter",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 143,
                            Age = "28",
                            Height = "198cm",
                            Number = 17,
                            PlayerName = "Ronald Daniel Fayola Hurtado",
                            Position = "Outside Hitter",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 144,
                            Age = "28",
                            Height = "194cm",
                            Number = 19,
                            PlayerName = "Willner Enrique Rivas Quijada",
                            Position = "Outside Hitter",
                            TeamName = "Venezuela"
                        });
                });

            modelBuilder.Entity("VolleyballFinal.Models.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AttackPoints")
                        .HasColumnType("int");

                    b.Property<int>("BlockPoints")
                        .HasColumnType("int");

                    b.Property<double>("Efficiency")
                        .HasColumnType("float");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServePoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("VolleyballFinal.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeagueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Argentina",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Brazil",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Canada",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "France",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Iran",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Italy",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Japan",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Poland",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Russia",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Tunisia",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "United States",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Venezuela",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Texas, Austin TX",
                            TeamName = "Texas"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Kansas, Lawrence KS",
                            TeamName = "Kansas"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Brigham Young University, Provo UT",
                            TeamName = "BYU"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Central Florida, Orlando FL",
                            TeamName = "UCF"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Baylor University, Waco TX",
                            TeamName = "Baylor"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Iowa State University, Ames IA",
                            TeamName = "Iowa State"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Houston, Houston TX",
                            TeamName = "Houston"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Kansas State University, Manhattan KS",
                            TeamName = "Kansas State"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Texas Christian University, Fort Worth TX",
                            TeamName = "TCU"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Cincinnati, Cincinnati OH",
                            TeamName = "Cincinnati"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Oklahoma, Norman OK",
                            TeamName = "Oklahoma"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "West Virginia University, Morgantown WV",
                            TeamName = "West Virginia"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Texas Tech University, Lubbock TX",
                            TeamName = "Texas Tech"
                        });
                });

            modelBuilder.Entity("VolleyballFinal.Models.Player", b =>
                {
                    b.HasOne("VolleyballFinal.Models.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("VolleyballFinal.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
