// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolleyballFinal.Models;

#nullable disable

namespace VolleyballFinal.Migrations
{
    [DbContext(typeof(TeamContext))]
    partial class TeamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VolleyballFinal.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("VolleyballFinal.Models.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AttackPoints")
                        .HasColumnType("int");

                    b.Property<int>("BlockPoints")
                        .HasColumnType("int");

                    b.Property<double>("Efficiency")
                        .HasColumnType("float");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServePoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("VolleyballFinal.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeagueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Argentina",
                            TeamName = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Brazil",
                            TeamName = "Brazil"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Canada",
                            TeamName = "Canada"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "France",
                            TeamName = "France"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Iran",
                            TeamName = "Iran"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Italy",
                            TeamName = "Italy"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Japan",
                            TeamName = "Japan"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Poland",
                            TeamName = "Poland"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Russia",
                            TeamName = "ROC"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Tunisia",
                            TeamName = "Tunisia"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "United States",
                            TeamName = "USA"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Indoor",
                            Gender = "Men",
                            LeagueType = "2020 Olympics",
                            Location = "Venezuela",
                            TeamName = "Venezuela"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Texas, Austin TX",
                            TeamName = "Texas"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Kansas, Lawrence KS",
                            TeamName = "Kansas"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Brigham Young University, Provo UT",
                            TeamName = "BYU"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Central Florida, Orlando FL",
                            TeamName = "UCF"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Baylor University, Waco TX",
                            TeamName = "Baylor"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Iowa State University, Ames IA",
                            TeamName = "Iowa State"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Houston, Houston TX",
                            TeamName = "Houston"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Kansas State University, Manhattan KS",
                            TeamName = "Kansas State"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Texas Christian University, Fort Worth TX",
                            TeamName = "TCU"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Cincinnati, Cincinnati OH",
                            TeamName = "Cincinnati"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "University of Oklahoma, Norman OK",
                            TeamName = "Oklahoma"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "West Virginia University, Morgantown WV",
                            TeamName = "West Virginia"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Indoor",
                            Gender = "Women",
                            LeagueType = "Big 12 Conference",
                            Location = "Texas Tech University, Lubbock TX",
                            TeamName = "Texas Tech"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
