using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System.Data.Common;
using System.Reflection;
using VolleyballFinal.Models.Admin;

namespace VolleyballFinal.Models
{
    public class TeamContext : IdentityDbContext<User>
    {
        public TeamContext(DbContextOptions<TeamContext> options) : base(options) { }

        public DbSet<Team> Teams { get; set; }
        public DbSet<Player> Player { get; set; }
        public DbSet<Statistic> Statistics { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Team>().HasData(
                // 2020 Olympics
                new Team { Id = 1, TeamName = "Argentina", Location = "Argentina", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 2, TeamName = "Brazil", Location = "Brazil", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 3, TeamName = "Canada", Location = "Canada", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 4, TeamName = "France", Location = "France", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 5, TeamName = "Iran", Location = "Iran", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 6, TeamName = "Italy", Location = "Italy", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 7, TeamName = "Japan", Location = "Japan", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 8, TeamName = "Poland", Location = "Poland", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 9, TeamName = "ROC", Location = "Russia", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 10, TeamName = "Tunisia", Location = "Tunisia", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 11, TeamName = "USA", Location = "United States", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                new Team { Id = 12, TeamName = "Venezuela", Location = "Venezuela", LeagueType = "2020 Olympics", Category = "Indoor", Gender = "Men" },
                
                // Big 12
                new Team { Id = 13, TeamName = "Texas", Location = "University of Texas, Austin TX", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 14, TeamName = "Kansas", Location = "University of Kansas, Lawrence KS", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 15, TeamName = "BYU", Location = "Brigham Young University, Provo UT", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 16, TeamName = "UCF", Location = "University of Central Florida, Orlando FL", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 17, TeamName = "Baylor", Location = "Baylor University, Waco TX", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 18, TeamName = "Iowa State", Location = "Iowa State University, Ames IA", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 19, TeamName = "Houston", Location = "University of Houston, Houston TX", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 20, TeamName = "Kansas State", Location = "Kansas State University, Manhattan KS", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 21, TeamName = "TCU", Location = "Texas Christian University, Fort Worth TX", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 22, TeamName = "Cincinnati", Location = "University of Cincinnati, Cincinnati OH", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 23, TeamName = "Oklahoma", Location = "University of Oklahoma, Norman OK", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 24, TeamName = "West Virginia", Location = "West Virginia University, Morgantown WV", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" },
                new Team { Id = 25, TeamName = "Texas Tech", Location = "Texas Tech University, Lubbock TX", LeagueType = "Big 12 Conference", Category = "Indoor", Gender = "Women" }
            );

            modelBuilder.Entity<Player>()
                .HasKey(p => p.PlayerId);
            modelBuilder.Entity<Player>().HasData(
                // Argentina
                new Player { PlayerId = 1, PlayerName = "Matias Sanchez", Number = 1, TeamName = "Argentina", Position = "Setter", Age = "27", Height = "175cm" },
                new Player { PlayerId = 2, PlayerName = "Federico Pereyra", Number = 2, TeamName = "Argentina", Position = "Opposite Hitter", Age = "35", Height = "200cm" },
                new Player { PlayerId = 3, PlayerName = "Cristian Poglajen", Number = 6, TeamName = "Argentina", Position = "Outside Hitter", Age = "34", Height = "195cm" },
                new Player { PlayerId = 4, PlayerName = "Facundo Conte", Number = 7, TeamName = "Argentina", Position = "Outside Hitter", Age = "34", Height = "197cm" },
                new Player { PlayerId = 5, PlayerName = "Agustin Loser", Number = 8, TeamName = "Argentina", Position = "Middle Blocker", Age = "26", Height = "198cm" },
                new Player { PlayerId = 6, PlayerName = "Santiago Danani", Number = 9, TeamName = "Argentina", Position = "Libero", Age = "27", Height = "176cm" },
                new Player { PlayerId = 7, PlayerName = "Sebastian Sole", Number = 11, TeamName = "Argentina", Position = "Middle Blocker", Age = "32", Height = "200cm" },
                new Player { PlayerId = 8, PlayerName = "Bruno Lima", Number = 12, TeamName = "Argentina", Position = "Opposite Hitter", Age = "27", Height = "198cm" },
                new Player { PlayerId = 9, PlayerName = "Ezequiel Palacios", Number = 13, TeamName = "Argentina", Position = "Outside Hitter", Age = "31", Height = "198cm" },
                new Player { PlayerId = 10, PlayerName = "Luciano De Cecco", Number = 15, TeamName = "Argentina", Position = "Setter", Age = "35", Height = "191cm" },
                new Player { PlayerId = 11, PlayerName = "Nicolas Mendez", Number = 17, TeamName = "Argentina", Position = "Outside Hitter", Age = "31", Height = "191cm" },
                new Player { PlayerId = 12, PlayerName = "Martin Ramos", Number = 18, TeamName = "Argentina", Position = "Middle Blocker", Age = "32", Height = "197cm" },

                // Brazil
                new Player { PlayerId = 13, PlayerName = "Bruno Mossa Rezende", Number = 1, TeamName = "Brazil", Position = "Setter", Age = "37", Height = "190cm" },
                new Player { PlayerId = 14, PlayerName = "Maurício Borges Almeida Silva", Number = 5, TeamName = "Brazil", Position = "Outside Hitter", Age = "34", Height = "199cm" },
                new Player { PlayerId = 15, PlayerName = "Fernando Gil Kreling", Number = 6, TeamName = "Brazil", Position = "Setter", Age = "27", Height = "186cm" },
                new Player { PlayerId = 16, PlayerName = "Wallace De Souza", Number = 8, TeamName = "Brazil", Position = "Opposite Hitter", Age = "36", Height = "198cm" },
                new Player { PlayerId = 17, PlayerName = "Yoandy Leal Hidalgo", Number = 9, TeamName = "Brazil", Position = "Outside Hitter", Age = "35", Height = "202cm" },
                new Player { PlayerId = 18, PlayerName = "Isac Santos", Number = 12, TeamName = "Brazil", Position = "Middle Blocker", Age = "32", Height = "208cm" },
                new Player { PlayerId = 19, PlayerName = "Mauricio Luiz De Souza", Number = 13, TeamName = "Brazil", Position = "Middle Blocker", Age = "35", Height = "207cm" },
                new Player { PlayerId = 20, PlayerName = "Douglas Correia De Souza", Number = 14, TeamName = "Brazil", Position = "Outside Hitter", Age = "28", Height = "199cm" },
                new Player { PlayerId = 21, PlayerName = "Lucas Saatkamp", Number = 16, TeamName = "Brazil", Position = "Middle Blocker", Age = "37", Height = "209cm" },
                new Player { PlayerId = 22, PlayerName = "Thales Hoss", Number = 17, TeamName = "Brazil", Position = "Libero", Age = "34", Height = "190cm" },
                new Player { PlayerId = 23, PlayerName = "Ricardo Lucarelli Souza", Number = 18, TeamName = "Brazil", Position = "Outside Hitter", Age = "31", Height = "196cm" },
                new Player { PlayerId = 24, PlayerName = "Alan Souza", Number = 21, TeamName = "Brazil", Position = "Opposite Hitter", Age = "29", Height = "202cm" },

                // Canada
                new Player { PlayerId = 25, PlayerName = "Tyler Sanders", Number = 1, TeamName = "Canada", Position = "Setter", Age = "31", Height = "191cm" },
                new Player { PlayerId = 26, PlayerName = "Tyler Gordon Perrin", Number = 2, TeamName = "Canada", Position = "Outside Hitter", Age = "34", Height = "201cm" },
                new Player { PlayerId = 27, PlayerName = "Steven Marshall", Number = 3, TeamName = "Canada", Position = "Libero", Age = "33", Height = "191cm" },
                new Player { PlayerId = 28, PlayerName = "Nicholas Hoag", Number = 4, TeamName = "Canada", Position = "Outside Hitter", Age = "31", Height = "200cm" },
                new Player { PlayerId = 29, PlayerName = "Stephen Timothy Maar", Number = 7, TeamName = "Canada", Position = "Outside Hitter", Age = "28", Height = "201cm" },
                new Player { PlayerId = 30, PlayerName = "Jay Blankenau", Number = 9, TeamName = "Canada", Position = "Setter", Age = "34", Height = "194cm" },
                new Player { PlayerId = 31, PlayerName = "Ryan Joseph Sclater", Number = 10, TeamName = "Canada", Position = "Opposite Hitter", Age = "29", Height = "200cm" },
                new Player { PlayerId = 32, PlayerName = "Lucas Van Berkel", Number = 12, TeamName = "Canada", Position = "Middle Blocker", Age = "31", Height = "210cm" },
                new Player { PlayerId = 33, PlayerName = "Sharone Vernon-Evans", Number = 13, TeamName = "Canada", Position = "Opposite Hitter", Age = "25", Height = "206cm" },
                new Player { PlayerId = 34, PlayerName = "Graham Vigrass", Number = 17, TeamName = "Canada", Position = "Middle Blocker", Age = "34", Height = "205cm" },
                new Player { PlayerId = 35, PlayerName = "Blair Cameron Bann", Number = 19, TeamName = "Canada", Position = "Libero", Age = "35", Height = "184cm" },
                new Player { PlayerId = 36, PlayerName = "Arthur Szwarc", Number = 20, TeamName = "Canada", Position = "Opposite Hitter", Age = "28", Height = "209cm" },

                // France
                new Player { PlayerId = 37, PlayerName = "Barthélémy Chinenyeze", Number = 1, TeamName = "France", Position = "Middle Blocker", Age = "25", Height = "204cm" },
                new Player { PlayerId = 38, PlayerName = "Jenia Grebennikov", Number = 2, TeamName = "France", Position = "Libero", Age = "33", Height = "188cm" },
                new Player { PlayerId = 39, PlayerName = "Jean Patry", Number = 4, TeamName = "France", Position = "Opposite Hitter", Age = "26", Height = "207cm" },
                new Player { PlayerId = 40, PlayerName = "Benjamin Toniutti", Number = 6, TeamName = "France", Position = "Setter", Age = "34", Height = "183cm" },
                new Player { PlayerId = 41, PlayerName = "Kevin Tillie", Number = 7, TeamName = "France", Position = "Outside Hitter", Age = "33", Height = "200cm" },
                new Player { PlayerId = 42, PlayerName = "Earvin Ngapeth", Number = 9, TeamName = "France", Position = "Outside Hitter", Age = "32", Height = "194cm" },
                new Player { PlayerId = 43, PlayerName = "Antoine Brizard", Number = 11, TeamName = "France", Position = "Setter", Age = "29", Height = "196cm" },
                new Player { PlayerId = 44, PlayerName = "Stephen Boyer", Number = 12, TeamName = "France", Position = "Opposite Hitter", Age = "27", Height = "196cm" },
                new Player { PlayerId = 45, PlayerName = "Nicolas Le Goff", Number = 14, TeamName = "France", Position = "Middle Blocker", Age = "31", Height = "206cm" },
                new Player { PlayerId = 46, PlayerName = "Daryl Bultor", Number = 16, TeamName = "France", Position = "Middle Blocker", Age = "27", Height = "197cm" },
                new Player { PlayerId = 47, PlayerName = "Trevor Clevenot", Number = 17, TeamName = "France", Position = "Outside Hitter", Age = "29", Height = "199cm" },
                new Player { PlayerId = 48, PlayerName = "Yacine Louati", Number = 19, TeamName = "France", Position = "Outside Hitter", Age = "31", Height = "198cm" },

                // Iran
                new Player { PlayerId = 49, PlayerName = "Milad Ebadipour Ghara H.", Number = 2, TeamName = "Iran", Position = "Outside Hitter", Age = "30", Height = "196cm" },
                new Player { PlayerId = 50, PlayerName = "Mir Saeid Marouflakrani", Number = 4, TeamName = "Iran", Position = "Setter", Age = "38", Height = "189cm" },
                new Player { PlayerId = 51, PlayerName = "Seyed Mohammad Mousavi Eraghi", Number = 6, TeamName = "Iran", Position = "Middle Blocker", Age = "36", Height = "203cm" },
                new Player { PlayerId = 52, PlayerName = "Masoud Gholami", Number = 9, TeamName = "Iran", Position = "Middle Blocker", Age = "33", Height = "204cm" },
                new Player { PlayerId = 53, PlayerName = "Amir Ghafour", Number = 10, TeamName = "Iran", Position = "Opposite Hitter", Age = "32", Height = "202cm" },
                new Player { PlayerId = 54, PlayerName = "Saber Kazemi", Number = 11, TeamName = "Iran", Position = "Opposite Hitter", Age = "24", Height = "205cm" },
                new Player { PlayerId = 55, PlayerName = "Morteza Sharifi", Number = 12, TeamName = "Iran", Position = "Outside Hitter", Age = "24", Height = "193cm" },
                new Player { PlayerId = 56, PlayerName = "Aliasghar Mojarad", Number = 15, TeamName = "Iran", Position = "Middle Blocker", Age = "26", Height = "205cm" },
                new Player { PlayerId = 57, PlayerName = "Meisam Salehi", Number = 17, TeamName = "Iran", Position = "Outside Hitter", Age = "24", Height = "198cm" },
                new Player { PlayerId = 58, PlayerName = "Mahdi Marandi", Number = 19, TeamName = "Iran", Position = "Libero", Age = "37", Height = "172cm" },
                new Player { PlayerId = 59, PlayerName = "Arman Salehi", Number = 21, TeamName = "Iran", Position = "Libero", Age = "31", Height = "180cm" },
                new Player { PlayerId = 60, PlayerName = "Javad Karimisouchelmaei", Number = 24, TeamName = "Iran", Position = "Setter", Age = "25", Height = "204cm" },

                // Italy
                new Player { PlayerId = 61, PlayerName = "Jiri Kovar", Number = 2, TeamName = "Italy", Position = "Outside Hitter", Age = "34", Height = "202cm" },
                new Player { PlayerId = 62, PlayerName = "Luca Vettori", Number = 4, TeamName = "Italy", Position = "Opposite Hitter", Age = "32", Height = "200cm" },
                new Player { PlayerId = 63, PlayerName = "Osmany Juantorena", Number = 5, TeamName = "Italy", Position = "Outside Hitter", Age = "38", Height = "200cm" },
                new Player { PlayerId = 64, PlayerName = "Simone Giannelli", Number = 6, TeamName = "Italy", Position = "Setter", Age = "27", Height = "200cm" },
                new Player { PlayerId = 65, PlayerName = "Ivan Zaytsev", Number = 9, TeamName = "Italy", Position = "Outside Hitter", Age = "35", Height = "204cm" },
                new Player { PlayerId = 66, PlayerName = "Matteo Piano", Number = 11, TeamName = "Italy", Position = "Middle Blocker", Age = "33", Height = "208cm" },
                new Player { PlayerId = 67, PlayerName = "Massimo Colaci", Number = 13, TeamName = "Italy", Position = "Libero", Age = "38", Height = "180cm" },
                new Player { PlayerId = 68, PlayerName = "Gianluca Galassi", Number = 14, TeamName = "Italy", Position = "Middle Blocker", Age = "26", Height = "201cm" },
                new Player { PlayerId = 69, PlayerName = "Riccardo Sbertoli", Number = 15, TeamName = "Italy", Position = "Setter", Age = "25", Height = "188cm" },
                new Player { PlayerId = 70, PlayerName = "Simone Anzani", Number = 17, TeamName = "Italy", Position = "Middle Blocker", Age = "31", Height = "204cm" },
                new Player { PlayerId = 71, PlayerName = "Alessandro Michieletto", Number = 18, TeamName = "Italy", Position = "Outside Hitter", Age = "21", Height = "205cm" },
                new Player { PlayerId = 72, PlayerName = "Daniele Lavia", Number = 19, TeamName = "Italy", Position = "Outside Hitter", Age = "24", Height = "200cm" },

                // Japan
                new Player { PlayerId = 73, PlayerName = "Kunihiro Shimizu", Number = 1, TeamName = "Japan", Position = "Opposite Hitter", Age = "37", Height = "193cm" },
                new Player { PlayerId = 74, PlayerName = "Taishi Onodera", Number = 2, TeamName = "Japan", Position = "Middle Blocker", Age = "27", Height = "200cm" },
                new Player { PlayerId = 75, PlayerName = "Naonobu Fujii", Number = 3, TeamName = "Japan", Position = "Setter", Age = "31", Height = "183cm" },
                new Player { PlayerId = 76, PlayerName = "Akihiro Yamauchi", Number = 6, TeamName = "Japan", Position = "Middle Blocker", Age = "29", Height = "204cm" },
                new Player { PlayerId = 77, PlayerName = "Yuji Nishida", Number = 11, TeamName = "Japan", Position = "Opposite Hitter", Age = "23", Height = "187cm" },
                new Player { PlayerId = 78, PlayerName = "Masahiro Sekita", Number = 12, TeamName = "Japan", Position = "Setter", Age = "29", Height = "175cm" },
                new Player { PlayerId = 79, PlayerName = "Yuki Ishikawa", Number = 14, TeamName = "Japan", Position = "Outside Hitter", Age = "27", Height = "191cm" },
                new Player { PlayerId = 80, PlayerName = "Haku Ri", Number = 15, TeamName = "Japan", Position = "Middle Blocker", Age = "32", Height = "193cm" },
                new Player { PlayerId = 81, PlayerName = "Kenta Takanashi", Number = 17, TeamName = "Japan", Position = "Outside Hitter", Age = "26", Height = "190cm" },
                new Player { PlayerId = 82, PlayerName = "Tatsunori Otsuka", Number = 19, TeamName = "Japan", Position = "Outside Hitter", Age = "22", Height = "194cm" },
                new Player { PlayerId = 83, PlayerName = "Tomohiro Yamamoto", Number = 20, TeamName = "Japan", Position = "Libero", Age = "28", Height = "171cm" },
                new Player { PlayerId = 84, PlayerName = "Ran Takahashi", Number = 21, TeamName = "Japan", Position = "Outside Hitter", Age = "22", Height = "188cm" },

                // Poland
                new Player { PlayerId = 85, PlayerName = "Piotr Nowakowski", Number = 1, TeamName = "Poland", Position = "Middle Blocker", Age = "35", Height = "205cm" },
                new Player { PlayerId = 86, PlayerName = "Lukasz Kaczmarek", Number = 5, TeamName = "Poland", Position = "Opposite Hitter", Age = "29", Height = "204cm" },
                new Player { PlayerId = 87, PlayerName = "Bartosz Kurek", Number = 6, TeamName = "Poland", Position = "Opposite Hitter", Age = "35", Height = "205cm" },
                new Player { PlayerId = 88, PlayerName = "Wilfredo Leon Venero", Number = 9, TeamName = "Poland", Position = "Outside Hitter", Age = "30", Height = "202cm" },
                new Player { PlayerId = 89, PlayerName = "Fabian Drzyzga", Number = 11, TeamName = "Poland", Position = "Setter", Age = "33", Height = "196cm" },
                new Player { PlayerId = 90, PlayerName = "Grzegorz Lomacz", Number = 12, TeamName = "Poland", Position = "Setter", Age = "36", Height = "187cm" },
                new Player { PlayerId = 91, PlayerName = "Michal Kubiak", Number = 13, TeamName = "Poland", Position = "Outside Hitter", Age = "35", Height = "191cm" },
                new Player { PlayerId = 92, PlayerName = "Aleksander Sliwka", Number = 14, TeamName = "Poland", Position = "Outside Hitter", Age = "28", Height = "196cm" },
                new Player { PlayerId = 93, PlayerName = "Jakub Kochanowski", Number = 15, TeamName = "Poland", Position = "Middle Blocker", Age = "26", Height = "199cm" },
                new Player { PlayerId = 94, PlayerName = "Kamil Semeniuk", Number = 16, TeamName = "Poland", Position = "Outside Hitter", Age = "27", Height = "195cm" },
                new Player { PlayerId = 95, PlayerName = "Pawel Zatorski", Number = 17, TeamName = "Poland", Position = "Libero", Age = "33", Height = "184cm" },
                new Player { PlayerId = 96, PlayerName = "Mateusz Bieniek", Number = 20, TeamName = "Poland", Position = "Middle Blocker", Age = "29", Height = "210cm" },

                // ROC (Russia)
                new Player { PlayerId = 97, PlayerName = "Yaroslav Podlesnykh", Number = 1, TeamName = "ROC", Position = "Outside Hitter", Age = "29", Height = "198cm" },
                new Player { PlayerId = 98, PlayerName = "Artem Volvich", Number = 4, TeamName = "ROC", Position = "Middle Blocker", Age = "33", Height = "208cm" },
                new Player { PlayerId = 99, PlayerName = "Dmitry Volkov", Number = 7, TeamName = "ROC", Position = "Outside Hitter", Age = "28", Height = "201cm" },
                new Player { PlayerId = 100, PlayerName = "Ivan Iakovlev", Number = 9, TeamName = "ROC", Position = "Middle Blocker", Age = "28", Height = "207cm" },
                new Player { PlayerId = 101, PlayerName = "Denis Bogdan", Number = 10, TeamName = "ROC", Position = "Outside Hitter", Age = "27", Height = "200cm" },
                new Player { PlayerId = 102, PlayerName = "Pavel Pankov", Number = 11, TeamName = "ROC", Position = "Setter", Age = "28", Height = "198cm" },
                new Player { PlayerId = 103, PlayerName = "Victor Poletaev", Number = 15, TeamName = "ROC", Position = "Opposite Hitter", Age = "28", Height = "197cm" },
                new Player { PlayerId = 104, PlayerName = "Maxim Mikhaylov", Number = 17, TeamName = "ROC", Position = "Opposite Hitter", Age = "35", Height = "202cm" },
                new Player { PlayerId = 105, PlayerName = "Egor Kliuka", Number = 18, TeamName = "ROC", Position = "Outside Hitter", Age = "28", Height = "209cm" },
                new Player { PlayerId = 106, PlayerName = "Ilyas Kurkaev", Number = 20, TeamName = "ROC", Position = "Middle Blocker", Age = "29", Height = "207cm" },
                new Player { PlayerId = 107, PlayerName = "Igor Kobzar", Number = 24, TeamName = "ROC", Position = "Setter", Age = "32", Height = "198cm" },
                new Player { PlayerId = 108, PlayerName = "Valentin Golubev", Number = 27, TeamName = "ROC", Position = "Libero", Age = "31", Height = "190cm" },

                // Tunisia
                new Player { PlayerId = 109, PlayerName = "Ahmed Kadhi", Number = 2, TeamName = "Tunisia", Position = "Middle Blocker", Age = "34", Height = "199cm" },
                new Player { PlayerId = 110, PlayerName = "Khaled Ben Slimene", Number = 3, TeamName = "Tunisia", Position = "Setter", Age = "28", Height = "193cm" },
                new Player { PlayerId = 111, PlayerName = "Mohamed Ali Ben Othmen", Number = 6, TeamName = "Tunisia", Position = "Outside Hitter", Age = "32", Height = "188cm" },
                new Player { PlayerId = 112, PlayerName = "Elyes Karamosli", Number = 7, TeamName = "Tunisia", Position = "Outside Hitter", Age = "34", Height = "198cm" },
                new Player { PlayerId = 113, PlayerName = "Omar Agrebi", Number = 9, TeamName = "Tunisia", Position = "Middle Blocker", Age = "31", Height = "205cm" },
                new Player { PlayerId = 114, PlayerName = "Hamza Nagga", Number = 10, TeamName = "Tunisia", Position = "Opposite Hitter", Age = "33", Height = "191cm" },
                new Player { PlayerId = 115, PlayerName = "Ismail Moalla", Number = 11, TeamName = "Tunisia", Position = "Outside Hitter", Age = "33", Height = "195cm" },
                new Player { PlayerId = 116, PlayerName = "Mehdi Ben Cheikh", Number = 12, TeamName = "Tunisia", Position = "Setter", Age = "44", Height = "184cm" },
                new Player { PlayerId = 117, PlayerName = "Selim Mbareki", Number = 13, TeamName = "Tunisia", Position = "Middle Blocker", Age = "27", Height = "198cm" },
                new Player { PlayerId = 118, PlayerName = "Wassim Ben Tara", Number = 15, TeamName = "Tunisia", Position = "Opposite Hitter", Age = "27", Height = "199cm" },
                new Player { PlayerId = 119, PlayerName = "Aymen Bouguerra", Number = 19, TeamName = "Tunisia", Position = "Outside Hitter", Age = "22", Height = "188cm" },
                new Player { PlayerId = 120, PlayerName = "Saddem Hmissi", Number = 20, TeamName = "Tunisia", Position = "Libero", Age = "32", Height = "186cm" },

                // USA
                new Player { PlayerId = 121, PlayerName = "Matthew Anderson", Number = 1, TeamName = "USA", Position = "Opposite Hitter", Age = "36", Height = "202cm" },
                new Player { PlayerId = 122, PlayerName = "Taylor Sander", Number = 3, TeamName = "USA", Position = "Outside Hitter", Age = "31", Height = "196cm" },
                new Player { PlayerId = 123, PlayerName = "Kyle Ensing", Number = 5, TeamName = "USA", Position = "Opposite Hitter", Age = "26", Height = "201cm" },
                new Player { PlayerId = 124, PlayerName = "Mitchell Stahl", Number = 6, TeamName = "USA", Position = "Middle Blocker", Age = "29", Height = "203cm" },
                new Player { PlayerId = 125, PlayerName = "Kawika Shoji", Number = 7, TeamName = "USA", Position = "Setter", Age = "35", Height = "190cm" },
                new Player { PlayerId = 126, PlayerName = "Torey Defalco", Number = 8, TeamName = "USA", Position = "Outside Hitter", Age = "26", Height = "198cm" },
                new Player { PlayerId = 127, PlayerName = "Micah Christenson", Number = 11, TeamName = "USA", Position = "Setter", Age = "30", Height = "198cm" },
                new Player { PlayerId = 128, PlayerName = "Maxwell Holt", Number = 12, TeamName = "USA", Position = "Middle Blocker", Age = "36", Height = "205cm" },
                new Player { PlayerId = 129, PlayerName = "Thomas Jaeschke", Number = 17, TeamName = "USA", Position = "Outside Hitter", Age = "30", Height = "198cm" },
                new Player { PlayerId = 130, PlayerName = "Garrett Muagututia", Number = 18, TeamName = "USA", Position = "Outside Hitter", Age = "35", Height = "205cm" },
                new Player { PlayerId = 131, PlayerName = "David Smith", Number = 20, TeamName = "USA", Position = "Middle Blocker", Age = "38", Height = "201cm" },
                new Player { PlayerId = 132, PlayerName = "Erik Shoji", Number = 22, TeamName = "USA", Position = "Libero", Age = "34", Height = "184cm" },

                // Venezuela
                new Player { PlayerId = 133, PlayerName = "Armando Fernando Velasquez Escalante", Number = 1, TeamName = "Venezuela", Position = "Setter", Age = "35", Height = "185cm" },
                new Player { PlayerId = 134, PlayerName = "Fernando Gonzalez", Number = 3, TeamName = "Venezuela", Position = "Outside Hitter", Age = "34", Height = "194cm" },
                new Player { PlayerId = 135, PlayerName = "Héctor Mata", Number = 4, TeamName = "Venezuela", Position = "Libero", Age = "32", Height = "179cm" },
                new Player { PlayerId = 136, PlayerName = "Emerson Alexander Rodriguez Gonzalez", Number = 5, TeamName = "Venezuela", Position = "Opposite Hitter", Age = "30", Height = "204cm" },
                new Player { PlayerId = 137, PlayerName = "Robert Manuel Oramas Brizuela", Number = 6, TeamName = "Venezuela", Position = "Middle Blocker", Age = "39", Height = "200cm" },
                new Player { PlayerId = 138, PlayerName = "Edson Alberto Valencia Gonzalez", Number = 7, TeamName = "Venezuela", Position = "Middle Blocker", Age = "35", Height = "200cm" },
                new Player { PlayerId = 139, PlayerName = "Jose Manuel Carrasco Angulo", Number = 9, TeamName = "Venezuela", Position = "Setter", Age = "34", Height = "192cm" },
                new Player { PlayerId = 140, PlayerName = "José Verdi", Number = 11, TeamName = "Venezuela", Position = "Middle Blocker", Age = "33", Height = "196cm" },
                new Player { PlayerId = 141, PlayerName = "Eliecer Alfonso Canelo Sanchez", Number = 14, TeamName = "Venezuela", Position = "Outside Hitter", Age = "25", Height = "196cm" },
                new Player { PlayerId = 142, PlayerName = "Luis Antonio Arias Guzman", Number = 15, TeamName = "Venezuela", Position = "Opposite Hitter", Age = "34", Height = "196cm" },
                new Player { PlayerId = 143, PlayerName = "Ronald Daniel Fayola Hurtado", Number = 17, TeamName = "Venezuela", Position = "Outside Hitter", Age = "28", Height = "198cm" },
                new Player { PlayerId = 144, PlayerName = "Willner Enrique Rivas Quijada", Number = 19, TeamName = "Venezuela", Position = "Outside Hitter", Age = "28", Height = "194cm" },

                // Texas
                new Player { PlayerId = 145, PlayerName = "Ella Swindle", Number = 1, TeamName = "Texas", Position = "Setter", Age = "Freshman", Height = "6'3\"" },
                new Player { PlayerId = 146, PlayerName = "Emma Halter", Number = 2, TeamName = "Texas", Position = "Libero", Age = "Sophomore", Height = "5'5\"" },
                new Player { PlayerId = 147, PlayerName = "Sydney Helmers", Number = 4, TeamName = "Texas", Position = "Outside Hitter", Age = "Freshman", Height = "6'4\"" },
                new Player { PlayerId = 148, PlayerName = "Bella Bergmark", Number = 5, TeamName = "Texas", Position = "Middle Blocker", Age = "Senior", Height = "6'2\"" },
                new Player { PlayerId = 149, PlayerName = "Madisen Skinner", Number = 6, TeamName = "Texas", Position = "Outside Hitter", Age = "Junior", Height = "6'2\"" },
                new Player { PlayerId = 150, PlayerName = "Asjia O'Neal", Number = 7, TeamName = "Texas", Position = "Middle Blocker", Age = "Senior", Height = "6'3\"" },
                new Player { PlayerId = 151, PlayerName = "Auburn Tomkinson", Number = 8, TeamName = "Texas", Position = "Opposite Hitter", Age = "Freshman", Height = "6'5\"" },
                new Player { PlayerId = 152, PlayerName = "Kenna Miller", Number = 9, TeamName = "Texas", Position = "Outside Hitter", Age = "Freshman", Height = "6'0\"" },
                new Player { PlayerId = 153, PlayerName = "Carissa Barnes", Number = 10, TeamName = "Texas", Position = "Libero", Age = "Senior", Height = "5'7\"" },
                new Player { PlayerId = 154, PlayerName = "Marianna Singletary", Number = 11, TeamName = "Texas", Position = "Middle Blocker", Age = "Freshman", Height = "6'4\"" },
                new Player { PlayerId = 155, PlayerName = "Keonilei Akana", Number = 12, TeamName = "Texas", Position = "Libero", Age = "Junior", Height = "5'9\"" },
                new Player { PlayerId = 156, PlayerName = "Jenna Wenaas", Number = 13, TeamName = "Texas", Position = "Outside Hitter", Age = "Junior", Height = "6'1\"" },
                new Player { PlayerId = 157, PlayerName = "Jordyn Byrd", Number = 14, TeamName = "Texas", Position = "Outside Hitter", Age = "Freshman", Height = "6'4\"" },
                new Player { PlayerId = 158, PlayerName = "Molly Phillips", Number = 15, TeamName = "Texas", Position = "Opposite Hitter", Age = "Senior", Height = "6'5\"" },
                new Player { PlayerId = 159, PlayerName = "Reilly Heinrich", Number = 19, TeamName = "Texas", Position = "Libero", Age = "Junior", Height = "5'6\"" },
                new Player { PlayerId = 160, PlayerName = "Mariana Crownover", Number = 22, TeamName = "Texas", Position = "Setter", Age = "Freshman", Height = "5'10\"" },
                new Player { PlayerId = 161, PlayerName = "Devin Kahahawai", Number = 44, TeamName = "Texas", Position = "Outside Hitter", Age = "Sophomore", Height = "6'4\"" },
                new Player { PlayerId = 162, PlayerName = "Nya Bunton", Number = 55, TeamName = "Texas", Position = "Middle Blocker", Age = "Freshman", Height = "6'3\"" },
                new Player { PlayerId = 163, PlayerName = "Kennedy Farris", Number = 1, TeamName = "Kansas", Position = "Libero", Age = "Senior", Height = "5'7\"" },

                // Kansas
                new Player { PlayerId = 164, PlayerName = "Raegan Burns", Number = 3, TeamName = "Kansas", Position = "Libero", Age = "Freshman", Height = "5'5\"" },
                new Player { PlayerId = 165, PlayerName = "Rhian Swanson", Number = 4, TeamName = "Kansas", Position = "Outside Hitter", Age = "Sophomore", Height = "6'2\"" },
                new Player { PlayerId = 166, PlayerName = "Bryn McGehe", Number = 5, TeamName = "Kansas", Position = "Libero", Age = "Sophomore", Height = "5'6\"" },
                new Player { PlayerId = 167, PlayerName = "Molly Schultz", Number = 6, TeamName = "Kansas", Position = "Libero", Age = "Senior", Height = "5'7\"" },
                new Player { PlayerId = 168, PlayerName = "Katie Dalton", Number = 7, TeamName = "Kansas", Position = "Setter", Age = "Sophomore", Height = "6'1\"" },
                new Player { PlayerId = 169, PlayerName = "Reagan Cooper", Number = 8, TeamName = "Kansas", Position = "Outside", Age = "Graduate", Height = "6'2\"" },
                new Player { PlayerId = 170, PlayerName = "Kim Whetstone", Number = 10, TeamName = "Kansas", Position = "Middle Blocker", Age = "Senior", Height = "6'0\"" },
                new Player { PlayerId = 171, PlayerName = "Toyosi Onabanjo", Number = 11, TeamName = "Kansas", Position = "Middle Blocker", Age = "Junior", Height = "6'1\"" },
                new Player { PlayerId = 172, PlayerName = "Mykayla Myers", Number = 12, TeamName = "Kansas", Position = "Middle Blocker", Age = "Graduate", Height = "6'1\"" },
                new Player { PlayerId = 173, PlayerName = "Kaiti Parks", Number = 13, TeamName = "Kansas", Position = "Middle Blocker", Age = "Junior", Height = "6'2\"" },
                new Player { PlayerId = 174, PlayerName = "Caroline Bien", Number = 14, TeamName = "Kansas", Position = "Outside Hitter", Age = "Junior", Height = "6'0\"" },
                new Player { PlayerId = 175, PlayerName = "Ellie Schneider", Number = 15, TeamName = "Kansas", Position = "Middle Blocker", Age = "Freshman", Height = "6'5\"" },
                new Player { PlayerId = 176, PlayerName = "Ayah Elnady", Number = 17, TeamName = "Kansas", Position = "Outside Hitter", Age = "Junior", Height = "5'10\"" },
                new Player { PlayerId = 177, PlayerName = "Molly McCarthy", Number = 19, TeamName = "Kansas", Position = "Libero", Age = "Sophomore", Height = "5'11\"" },
                new Player { PlayerId = 178, PlayerName = "Brynn Kirsch", Number = 20, TeamName = "Kansas", Position = "Libero", Age = "Sophomore", Height = "5'8\"" },
                new Player { PlayerId = 179, PlayerName = "London Davis", Number = 21, TeamName = "Kansas", Position = "Opposite", Age = "Junior", Height = "6'0\"" },
                new Player { PlayerId = 180, PlayerName = "Camryn Turner", Number = 22, TeamName = "Kansas", Position = "Setter", Age = "Junior", Height = "5'8\"" },
                new Player { PlayerId = 181, PlayerName = "Aisha Aiono", Number = 24, TeamName = "Kansas", Position = "Middle Blocker", Age = "Freshman", Height = "6'3\"" },

                // BYU
                new Player { PlayerId = 182, PlayerName = "Kate Prior", Number = 1, TeamName = "BYU", Position = "Opposite Hitter", Age = "Sophomore", Height = "6'4\"" },
                new Player { PlayerId = 183, PlayerName = "Silina Damuni", Number = 3, TeamName = "BYU", Position = "Setter", Age = "Freshman", Height = "5'9\"" },
                new Player { PlayerId = 184, PlayerName = "Hannah Billeter", Number = 4, TeamName = "BYU", Position = "Libero", Age = "Sophomore", Height = "5'11\"" },
                new Player { PlayerId = 185, PlayerName = "Kalia Thunstrom", Number = 6, TeamName = "BYU", Position = "Setter", Age = "Junior", Height = "5'10\"" },
                new Player { PlayerId = 186, PlayerName = "Whitney Bower", Number = 7, TeamName = "BYU", Position = "Setter", Age = "Senior", Height = "5'9\"" },
                new Player { PlayerId = 187, PlayerName = "Eden Bower", Number = 8, TeamName = "BYU", Position = "Outside Hitter", Age = "Sophomore", Height = "6'3\"" },
                new Player { PlayerId = 188, PlayerName = "Alyssa Erickson", Number = 9, TeamName = "BYU", Position = "Outside Hitter", Age = "Junior", Height = "6'1\"" },
                new Player { PlayerId = 189, PlayerName = "Erin Livingston", Number = 10, TeamName = "BYU", Position = "Outside Hitter", Age = "Senior", Height = "6'2\"" },
                new Player { PlayerId = 190, PlayerName = "Addie Benson", Number = 11, TeamName = "BYU", Position = "Outside Hitter", Age = "Freshman", Height = "6'2\"" },
                new Player { PlayerId = 191, PlayerName = "Claire Little", Number = 12, TeamName = "BYU", Position = "Outside Hitter", Age = "Freshman", Height = "6'3\"" },
                new Player { PlayerId = 192, PlayerName = "Mia Lee", Number = 13, TeamName = "BYU", Position = "Middle Blocker", Age = "Freshman", Height = "6'0\"" },
                new Player { PlayerId = 193, PlayerName = "Aria McComber", Number = 14, TeamName = "BYU", Position = "Libero", Age = "Graduate", Height = "5'6\"" },
                new Player { PlayerId = 194, PlayerName = "Elyse Stowell", Number = 15, TeamName = "BYU", Position = "Outside Hitter", Age = "Junior", Height = "6'2\"" },
                new Player { PlayerId = 195, PlayerName = "Brielle Miller", Number = 16, TeamName = "BYU", Position = "Libero", Age = "Freshman", Height = "5'5\"" },
                new Player { PlayerId = 196, PlayerName = "Kamaile Hiapo", Number = 18, TeamName = "BYU", Position = "Libero", Age = "Graduate", Height = "5'7\"" },
                new Player { PlayerId = 197, PlayerName = "Whitney McEwan-Llarenas", Number = 21, TeamName = "BYU", Position = "Middle Blocker", Age = "Graduate", Height = "6'3\"" },
                new Player { PlayerId = 198, PlayerName = "Brielle Kemavor", Number = 24, TeamName = "BYU", Position = "Middle Blocker", Age = "Freshman", Height = "6'5\"" },

                // UCF
                new Player { PlayerId = 199, PlayerName = "Abby Schomers", Number = 1, TeamName = "UCF", Position = "Setter", Age = "Freshman", Height = "6'0\"" },
                new Player { PlayerId = 200, PlayerName = "Chloe Scheer", Number = 2, TeamName = "UCF", Position = "Libero", Age = "Senior", Height = "5'8\"" },
                new Player { PlayerId = 201, PlayerName = "Sasha Cohen", Number = 3, TeamName = "UCF", Position = "Middle Blocker", Age = "Freshman", Height = "6'2\"" },
                new Player { PlayerId = 202, PlayerName = "Megan Holland", Number = 4, TeamName = "UCF", Position = "Middle Blocker", Age = "Sophomore", Height = "6'4\"" },
                new Player { PlayerId = 203, PlayerName = "Doga Ocal", Number = 5, TeamName = "UCF", Position = "Outside Hitter", Age = "Freshman", Height = "6'2\"" },
                new Player { PlayerId = 204, PlayerName = "Annika Sokol", Number = 7, TeamName = "UCF", Position = "Libero", Age = "Freshman", Height = "5'10\"" },
                new Player { PlayerId = 205, PlayerName = "Abby Hansen", Number = 9, TeamName = "UCF", Position = "Middle Blocker", Age = "Graduate", Height = "6'5\"" },
                new Player { PlayerId = 206, PlayerName = "Avah Armour", Number = 10, TeamName = "UCF", Position = "Outside Hitter", Age = "Freshman", Height = "6'5\"" },
                new Player { PlayerId = 207, PlayerName = "Katelyn Grimes", Number = 11, TeamName = "UCF", Position = "Libero", Age = "Junior", Height = "5'6\"" },
                new Player { PlayerId = 208, PlayerName = "Heidi Bonde", Number = 12, TeamName = "UCF", Position = "Outside Hitter", Age = "Junior", Height = "6'4\"" },
                new Player { PlayerId = 209, PlayerName = "Lauren Clark", Number = 13, TeamName = "UCF", Position = "Outside Hitter", Age = "Graduate", Height = "6'0\"" },
                new Player { PlayerId = 210, PlayerName = "Claudia Dillon", Number = 15, TeamName = "UCF", Position = "Middle Blocker", Age = "Graduate", Height = "6'2\"" },
                new Player { PlayerId = 211, PlayerName = "Renee Ralls", Number = 18, TeamName = "UCF", Position = "Libero", Age = "Sophomore", Height = "5'11\"" },
                new Player { PlayerId = 212, PlayerName = "Britt Carlson", Number = 23, TeamName = "UCF", Position = "Outside Hitter", Age = "Freshman", Height = "6'4\"" },
                new Player { PlayerId = 213, PlayerName = "Emily Wilson", Number = 26, TeamName = "UCF", Position = "Outside Hitter", Age = "Junior", Height = "6'3\"" },

                // Baylor
                new Player { PlayerId = 214, PlayerName = "Harley Kreck", Number = 1, TeamName = "Baylor", Position = "Setter", Age = "Freshman", Height = "6'0\"" },
                new Player { PlayerId = 215, PlayerName = "Lauren Briseno", Number = 2, TeamName = "Baylor", Position = "Libero", Age = "Junior", Height = "5'7\"" },
                new Player { PlayerId = 216, PlayerName = "Averi Carlson", Number = 3, TeamName = "Baylor", Position = "Setter", Age = "Sophomore", Height = "5'11\"" },
                new Player { PlayerId = 217, PlayerName = "Allie Sczech", Number = 4, TeamName = "Baylor", Position = "Opposite Hitter", Age = "Sophomore", Height = "6'4\"" },
                new Player { PlayerId = 218, PlayerName = "Kyndal Stowers", Number = 5, TeamName = "Baylor", Position = "Outside Hitter", Age = "Freshman", Height = "5'11\"" },
                new Player { PlayerId = 219, PlayerName = "Faith Lynch", Number = 6, TeamName = "Baylor", Position = "Libero", Age = "Junior", Height = "5'7\"" },
                new Player { PlayerId = 220, PlayerName = "Victoria Davis", Number = 7, TeamName = "Baylor", Position = "Middle Blocker", Age = "Freshman", Height = "6'2\"" },
                new Player { PlayerId = 221, PlayerName = "Brianna Denney", Number = 8, TeamName = "Baylor", Position = "Setter", Age = "Sophomore", Height = "5'11\"" },
                new Player { PlayerId = 222, PlayerName = "Ava Grace Haggard", Number = 9, TeamName = "Baylor", Position = "Middle Blocker", Age = "Junior", Height = "6'1\"" },
                new Player { PlayerId = 223, PlayerName = "Sophia Keene", Number = 10, TeamName = "Baylor", Position = "Outside Hitter", Age = "Sophomore", Height = "6'2\"" },
                new Player { PlayerId = 224, PlayerName = "Kendal Murphy", Number = 11, TeamName = "Baylor", Position = "Outside Hitter", Age = "Freshman", Height = "6'3\"" },
                new Player { PlayerId = 225, PlayerName = "Joya Screen", Number = 12, TeamName = "Baylor", Position = "Middle Blocker", Age = "Freshman", Height = "6'3\"" },
                new Player { PlayerId = 226, PlayerName = "Riley Simpson", Number = 13, TeamName = "Baylor", Position = "Outside Hitter", Age = "Sophomore", Height = "6'4\"" },
                new Player { PlayerId = 227, PlayerName = "Alexis Dacosta", Number = 15, TeamName = "Baylor", Position = "Libero", Age = "Sophomore", Height = "5'11\"" },
                new Player { PlayerId = 228, PlayerName = "Alicia Andrew", Number = 18, TeamName = "Baylor", Position = "Middle Blocker", Age = "Sophomore", Height = "6'3\"" },
                new Player { PlayerId = 229, PlayerName = "Manuela Bibinbe", Number = 20, TeamName = "Baylor", Position = "Middle Blocker", Age = "Junior", Height = "6'3\"" },
                new Player { PlayerId = 230, PlayerName = "Elise McGhee", Number = 21, TeamName = "Baylor", Position = "Outside Hitter", Age = "Junior", Height = "6'4\"" },
                new Player { PlayerId = 231, PlayerName = "Tehani Ulufatu", Number = 26, TeamName = "Baylor", Position = "Libero", Age = "Freshman", Height = "5'5\"" },

                // Iowa State
                new Player { PlayerId = 232, PlayerName = "Pam McCune", Number = 1, TeamName = "Iowa State", Position = "Middle Blocker", Age = "Freshman", Height = "6' 0\"" },
                new Player { PlayerId = 233, PlayerName = "Morgan Brandt", Number = 2, TeamName = "Iowa State", Position = "Setter", Age = "Sophomore", Height = "6' 0\"" },
                new Player { PlayerId = 234, PlayerName = "Jordan Hopp", Number = 4, TeamName = "Iowa State", Position = "Middle Blocker", Age = "Senior", Height = "6' 2\"" },
                new Player { PlayerId = 235, PlayerName = "Maya Duckworth", Number = 5, TeamName = "Iowa State", Position = "Outside Hitter", Age = "Sophomore", Height = "5' 8\"" },
                new Player { PlayerId = 236, PlayerName = "Addi Heidemann", Number = 7, TeamName = "Iowa State", Position = "Setter", Age = "Sophomore", Height = "5' 10\"" },
                new Player { PlayerId = 237, PlayerName = "Brooke Stonestreet", Number = 8, TeamName = "Iowa State", Position = "Libero", Age = "Junior", Height = "5' 10\"" },
                new Player { PlayerId = 238, PlayerName = "Annie Hatch", Number = 9, TeamName = "Iowa State", Position = "Outside Hitter", Age = "Senior", Height = "6' 1\"" },
                new Player { PlayerId = 239, PlayerName = "Reaghan Larkin", Number = 11, TeamName = "Iowa State", Position = "Outside Hitter", Age = "Freshman", Height = "6' 2\"" },
                new Player { PlayerId = 240, PlayerName = "Alexis Engelbrecht", Number = 12, TeamName = "Iowa State", Position = "Middle Blocker", Age = "Senior", Height = "6' 2\"" },
                new Player { PlayerId = 241, PlayerName = "Lilly Wachholz", Number = 13, TeamName = "Iowa State", Position = "Outside Hitter", Age = "Freshman", Height = "6' 2\"" },
                new Player { PlayerId = 242, PlayerName = "Nayeli Gonzalez", Number = 14, TeamName = "Iowa State", Position = "Outside Hitter", Age = "Freshman", Height = "6' 2\"" },
                new Player { PlayerId = 243, PlayerName = "Kiersten Schmitt", Number = 15, TeamName = "Iowa State", Position = "Outside Hitter", Age = "Freshman", Height = "6' 0\"" },
                new Player { PlayerId = 244, PlayerName = "Kelsey Perry", Number = 18, TeamName = "Iowa State", Position = "Middle Blocker", Age = "Sophomore", Height = "6' 4\"" },
                new Player { PlayerId = 245, PlayerName = "Faith DeRonde", Number = 19, TeamName = "Iowa State", Position = "Outside Hitter", Age = "Sophomore", Height = "5' 11\"" },
                new Player { PlayerId = 246, PlayerName = "Paula Krzeslak", Number = 21, TeamName = "Iowa State", Position = "Libero", Age = "Sophomore", Height = "5' 6\"" },

                // Houston
                new Player { PlayerId = 247, PlayerName = "Morgan Janda", Number = 1, TeamName = "Houston", Position = "Setter", Age = "Graduate", Height = "5'10\"" },
                new Player { PlayerId = 248, PlayerName = "Alana Torres-Rivera", Number = 2, TeamName = "Houston", Position = "Libero", Age = "Sophomore", Height = "5'5\"" },
                new Player { PlayerId = 249, PlayerName = "Bryshanna Brown", Number = 3, TeamName = "Houston", Position = "Libero", Age = "Junior", Height = "5'8\"" },
                new Player { PlayerId = 250, PlayerName = "Kenna Sauer", Number = 4, TeamName = "Houston", Position = "Outside Hitter", Age = "Graduate", Height = "6'1\"" },
                new Player { PlayerId = 251, PlayerName = "Reagan Fifer", Number = 5, TeamName = "Houston", Position = "Setter", Age = "Freshman", Height = "6'2\"" },
                new Player { PlayerId = 252, PlayerName = "Ella Busey", Number = 6, TeamName = "Houston", Position = "Outside Hitter", Age = "Freshman", Height = "6'0\"" },
                new Player { PlayerId = 253, PlayerName = "Grace Wiley", Number = 7, TeamName = "Houston", Position = "Outside Hitter", Age = "Junior", Height = "6'2\"" },
                new Player { PlayerId = 254, PlayerName = "Kayla Knowles", Number = 8, TeamName = "Houston", Position = "Outside Hitter", Age = "Freshman", Height = "6'0\"" },
                new Player { PlayerId = 255, PlayerName = "Nena Mbonu", Number = 9, TeamName = "Houston", Position = "Outside Hitter", Age = "Graduate", Height = "6'0\"" },
                new Player { PlayerId = 256, PlayerName = "Rachel Tullos", Number = 11, TeamName = "Houston", Position = "Middle Blocker", Age = "Graduate", Height = "6'1\"" },
                new Player { PlayerId = 257, PlayerName = "Sunni Sheppard", Number = 12, TeamName = "Houston", Position = "Libero", Age = "Freshman", Height = "5'4\"" },
                new Player { PlayerId = 258, PlayerName = "Barakat Rahmon", Number = 13, TeamName = "Houston", Position = "Middle Blocker", Age = "Sophomore", Height = "6'1\"" },
                new Player { PlayerId = 259, PlayerName = "Ella Wendel", Number = 14, TeamName = "Houston", Position = "Middle Blocker", Age = "Freshman", Height = "6'1\"" },
                new Player { PlayerId = 260, PlayerName = "Kate Georgiades", Number = 17, TeamName = "Houston", Position = "Libero", Age = "Senior", Height = "5'9\"" },
                new Player { PlayerId = 261, PlayerName = "Annie Cooke", Number = 18, TeamName = "Houston", Position = "Setter", Age = "Senior", Height = "5'11\"" },
                new Player { PlayerId = 262, PlayerName = "Katie Corelli", Number = 21, TeamName = "Houston", Position = "Outside Hitter", Age = "Junior", Height = "6'1\"" },
                new Player { PlayerId = 263, PlayerName = "Kennedi Bray", Number = 22, TeamName = "Houston", Position = "Outside Hitter", Age = "Sophomore", Height = "6'2\"" },
                new Player { PlayerId = 264, PlayerName = "Ashlyn Bellamy", Number = 23, TeamName = "Houston", Position = "Outside Hitter", Age = "Freshman", Height = "6'1\"" },
                new Player { PlayerId = 265, PlayerName = "Abbie Jackson", Number = 24, TeamName = "Houston", Position = "Outside Hitter", Age = "Graduate", Height = "6'0\"" },
                new Player { PlayerId = 266, PlayerName = "Kellen Morin", Number = 25, TeamName = "Houston", Position = "Middle Blocker", Age = "Junior", Height = "6'4\"" },

                // Kansas State
                new Player { PlayerId = 267, PlayerName = "Liz Gregorski", Number = 1, TeamName = "Kansas State", Position = "Outside Hitter", Age = "Senior", Height = "5'11\"" },
                new Player { PlayerId = 268, PlayerName = "Aliyah Carter", Number = 2, TeamName = "Kansas State", Position = "Outside Hitter", Age = "Senior", Height = "5'10\"" },
                new Player { PlayerId = 269, PlayerName = "Molly Ramsey", Number = 3, TeamName = "Kansas State", Position = "Libero", Age = "Junior", Height = "5'4\"" },
                new Player { PlayerId = 270, PlayerName = "Kadye Fernholz", Number = 4, TeamName = "Kansas State", Position = "Middle Blocker", Age = "Senior", Height = "6'1\"" },
                new Player { PlayerId = 271, PlayerName = "Aniya Clinton", Number = 5, TeamName = "Kansas State", Position = "Outside Hitter", Age = "Freshman", Height = "6'2\"" },
                new Player { PlayerId = 272, PlayerName = "Makinsey Jones", Number = 6, TeamName = "Kansas State", Position = "Middle Blocker", Age = "Freshman", Height = "6'1\"" },
                new Player { PlayerId = 273, PlayerName = "Symone Sims", Number = 7, TeamName = "Kansas State", Position = "Libero", Age = "Freshman", Height = "5'5\"" },
                new Player { PlayerId = 274, PlayerName = "Lauren Schneider", Number = 9, TeamName = "Kansas State", Position = "Outside Hitter", Age = "Freshman", Height = "5'9\"" },
                new Player { PlayerId = 275, PlayerName = "Dalia Wilson", Number = 10, TeamName = "Kansas State", Position = "Opposite Hitter", Age = "Sophomore", Height = "6'4\"" },
                new Player { PlayerId = 276, PlayerName = "Ava LeGrand", Number = 11, TeamName = "Kansas State", Position = "Setter", Age = "Sophomore", Height = "6'0\"" },
                new Player { PlayerId = 277, PlayerName = "Loren Hinkle", Number = 12, TeamName = "Kansas State", Position = "Setter", Age = "Senior", Height = "5'9\"" },
                new Player { PlayerId = 278, PlayerName = "Shaylee Myers", Number = 14, TeamName = "Kansas State", Position = "Outside Hitter", Age = "Sophomore", Height = "6'0\"" },
                new Player { PlayerId = 279, PlayerName = "Izzi Szulczewski", Number = 15, TeamName = "Kansas State", Position = "Setter", Age = "Junior", Height = "5'7\"" },
                new Player { PlayerId = 280, PlayerName = "Sydney Bolding", Number = 16, TeamName = "Kansas State", Position = "Middle Blocker", Age = "Graduate", Height = "6'5\"" },
                new Player { PlayerId = 281, PlayerName = "Reagan Fox", Number = 17, TeamName = "Kansas State", Position = "Outside Hitter", Age = "Freshman", Height = "6'2\"" },
                new Player { PlayerId = 282, PlayerName = "Brenna Schmidt", Number = 18, TeamName = "Kansas State", Position = "Middle Blocker", Age = "Sophomore", Height = "6'6\"" },
                new Player { PlayerId = 283, PlayerName = "Mackenzie Morris", Number = 20, TeamName = "Kansas State", Position = "Libero", Age = "Senior", Height = "5'7\"" },

                // TCU
                new Player { PlayerId = 284, PlayerName = "Zoe Hall", Number = 1, TeamName = "TCU", Position = "Middle Blocker", Age = "Junior", Height = "6'3\"" },
                new Player { PlayerId = 285, PlayerName = "Riley Buckley", Number = 2, TeamName = "TCU", Position = "Setter", Age = "Sophomore", Height = "6'1\"" },
                new Player { PlayerId = 286, PlayerName = "Samiyah Abdur-Rahim", Number = 3, TeamName = "TCU", Position = "Outside Hitter", Age = "Freshman", Height = "6'2\"" },
                new Player { PlayerId = 287, PlayerName = "Sarah Sylvester", Number = 4, TeamName = "TCU", Position = "Middle Blocker", Age = "Sophomore", Height = "6'3\"" },
                new Player { PlayerId = 288, PlayerName = "Jalyn Gibson", Number = 5, TeamName = "TCU", Position = "Outside Hitter", Age = "Sophomore", Height = "6'2\"" },
                new Player { PlayerId = 289, PlayerName = "Taylor Raiola", Number = 6, TeamName = "TCU", Position = "Outside Hitter", Age = "Senior", Height = "6'0\"" },
                new Player { PlayerId = 290, PlayerName = "Brianna Green", Number = 10, TeamName = "TCU", Position = "Middle Blocker", Age = "Graduate", Height = "6'1\"" },
                new Player { PlayerId = 291, PlayerName = "Julia Adams", Number = 12, TeamName = "TCU", Position = "Outside Hitter", Age = "Graduate", Height = "6'3\"" },
                new Player { PlayerId = 292, PlayerName = "Audrey Nalls", Number = 15, TeamName = "TCU", Position = "Outside Hitter", Age = "Graduate", Height = "6'1\"" },
                new Player { PlayerId = 293, PlayerName = "Jaylen Clark", Number = 16, TeamName = "TCU", Position = "Libero", Age = "Freshman", Height = "5'7\"" },
                new Player { PlayerId = 294, PlayerName = "Megan Walsh", Number = 17, TeamName = "TCU", Position = "Libero", Age = "Freshman", Height = "5'9\"" },
                new Player { PlayerId = 295, PlayerName = "Eryn Jones", Number = 18, TeamName = "TCU", Position = "Outside Hitter", Age = "Freshman", Height = "6'0\"" },
                new Player { PlayerId = 296, PlayerName = "Lily Nicholson", Number = 21, TeamName = "TCU", Position = "Setter", Age = "Freshman", Height = "5'11\"" },
                new Player { PlayerId = 297, PlayerName = "Ashlyn Bourland", Number = 22, TeamName = "TCU", Position = "Setter", Age = "Sophomore", Height = "5'9\"" },
                new Player { PlayerId = 298, PlayerName = "Melanie Parra", Number = 23, TeamName = "TCU", Position = "Outside Hitter", Age = "Junior", Height = "5'11\"" },
                new Player { PlayerId = 299, PlayerName = "Alyssa Gonzales", Number = 24, TeamName = "TCU", Position = "Outside Hitter", Age = "Freshman", Height = "6'1\"" },
                new Player { PlayerId = 300, PlayerName = "Lydia Seymour", Number = 25, TeamName = "TCU", Position = "Middle Blocker", Age = "Freshman", Height = "6'5\"" },
                new Player { PlayerId = 301, PlayerName = "Riley Weigelt", Number = 33, TeamName = "TCU", Position = "Libero", Age = "Sophomore", Height = "5'9\"" },
                new Player { PlayerId = 302, PlayerName = "Cecily Bramschreiber", Number = 35, TeamName = "TCU", Position = "Libero", Age = "Junior", Height = "5'9\"" },

                // Cincinnati
                new Player { PlayerId = 303, PlayerName = "Nina Horning", Number = 1, TeamName = "Cincinnati", Position = "Outside Hitter", Age = "Freshman", Height = "6'5\"" },
                new Player { PlayerId = 304, PlayerName = "Katelyn Lefler", Number = 3, TeamName = "Cincinnati", Position = "Setter", Age = "Junior", Height = "6'0\"" },
                new Player { PlayerId = 305, PlayerName = "Carly Glendinning", Number = 4, TeamName = "Cincinnati", Position = "Outside Hitter", Age = "Sophomore", Height = "6'2\"" },
                new Player { PlayerId = 306, PlayerName = "Lilian Entenmann", Number = 5, TeamName = "Cincinnati", Position = "Middle Blocker", Age = "Freshman", Height = "6'1\"" },
                new Player { PlayerId = 307, PlayerName = "Jadyn Bauss", Number = 6, TeamName = "Cincinnati", Position = "Outside Hitter", Age = "Graduate", Height = "6'0\"" },
                new Player { PlayerId = 308, PlayerName = "Ligia Williams", Number = 8, TeamName = "Cincinnati", Position = "Middle Blocker", Age = "Sophomore", Height = "5'11\"" },
                new Player { PlayerId = 309, PlayerName = "Kayla Hostetler", Number = 9, TeamName = "Cincinnati", Position = "Libero", Age = "Freshman", Height = "5'6\"" },
                new Player { PlayerId = 310, PlayerName = "Elissa Alcantara", Number = 11, TeamName = "Cincinnati", Position = "Outside Hitter", Age = "Senior", Height = "6'2\"" },
                new Player { PlayerId = 311, PlayerName = "Shaye Eggleston", Number = 12, TeamName = "Cincinnati", Position = "Outside Hitter", Age = "Junior", Height = "6'0\"" },
                new Player { PlayerId = 312, PlayerName = "Carly Skrabak", Number = 14, TeamName = "Cincinnati", Position = "Libero", Age = "Graduate", Height = "5'6\"" },
                new Player { PlayerId = 313, PlayerName = "Paige Pickering", Number = 17, TeamName = "Cincinnati", Position = "Outside Hitter", Age = "Sophomore", Height = "5'10\"" },
                new Player { PlayerId = 314, PlayerName = "Vivian Campbell", Number = 19, TeamName = "Cincinnati", Position = "Setter", Age = "Freshman", Height = "5'10\"" },
                new Player { PlayerId = 315, PlayerName = "Caroline Endres", Number = 22, TeamName = "Cincinnati", Position = "Setter", Age = "Sophomore", Height = "5'10\"" },
                new Player { PlayerId = 316, PlayerName = "Abby Walker", Number = 24, TeamName = "Cincinnati", Position = "Middle Blocker", Age = "Junior", Height = "6'1\"" },
                new Player { PlayerId = 317, PlayerName = "Julie Wittekind", Number = 30, TeamName = "Cincinnati", Position = "Libero", Age = "Junior", Height = "5'8\"" },
                new Player { PlayerId = 318, PlayerName = "Molly Harrison", Number = 33, TeamName = "Cincinnati", Position = "Libero", Age = "Junior", Height = "5'9\"" },
                new Player { PlayerId = 319, PlayerName = "Zeta Washington", Number = 99, TeamName = "Cincinnati", Position = "Middle Blocker", Age = "Freshman", Height = "6'2\"" },

                // Oklahoma
                new Player { PlayerId = 320, PlayerName = "Kelsey Carrington", Number = 1, TeamName = "Oklahoma", Position = "Middle Blocker", Age = "Senior", Height = "6' 3\"" },
                new Player { PlayerId = 321, PlayerName = "Payton Chamberlain", Number = 2, TeamName = "Oklahoma", Position = "Setter", Age = "Junior", Height = "6' 0\"" },
                new Player { PlayerId = 322, PlayerName = "Rylee Fay", Number = 4, TeamName = "Oklahoma", Position = "Setter", Age = "Junior", Height = "5' 9\"" },
                new Player { PlayerId = 323, PlayerName = "Kristen Birmingham", Number = 5, TeamName = "Oklahoma", Position = "Opposite Hitter", Age = "Junior", Height = "6' 1\"" },
                new Player { PlayerId = 324, PlayerName = "Hannah Pfiffner", Number = 7, TeamName = "Oklahoma", Position = "Middle Blocker", Age = "Freshman", Height = "6' 1\"" },
                new Player { PlayerId = 325, PlayerName = "Mele Corral-Blagojevich", Number = 8, TeamName = "Oklahoma", Position = "Outside Hitter", Age = "Freshman", Height = "6' 1\"" },
                new Player { PlayerId = 326, PlayerName = "Callie Kemohah", Number = 10, TeamName = "Oklahoma", Position = "Libero", Age = "Junior", Height = "5' 6\"" },
                new Player { PlayerId = 327, PlayerName = "Emma Henry", Number = 11, TeamName = "Oklahoma", Position = "Setter", Age = "Freshman", Height = "5' 8\"" },
                new Player { PlayerId = 328, PlayerName = "Alexis Shelton", Number = 12, TeamName = "Oklahoma", Position = "Outside Hitter", Age = "Sophomore", Height = "6' 2\"" },
                new Player { PlayerId = 329, PlayerName = "Ireland McNees", Number = 16, TeamName = "Oklahoma", Position = "Outside Hitter", Age = "Freshman", Height = "5' 9\"" },
                new Player { PlayerId = 330, PlayerName = "Daleigh Ellison", Number = 17, TeamName = "Oklahoma", Position = "Outside Hitter", Age = "Junior", Height = "5' 11\"" },
                new Player { PlayerId = 331, PlayerName = "Lydia Burts", Number = 22, TeamName = "Oklahoma", Position = "Middle Blocker", Age = "Senior", Height = "6' 3\"" },
                new Player { PlayerId = 332, PlayerName = "Taylor Preston", Number = 23, TeamName = "Oklahoma", Position = "Outside Hitter", Age = "Sophomore", Height = "6' 2\"" },
                new Player { PlayerId = 333, PlayerName = "Sydney Thompson", Number = 24, TeamName = "Oklahoma", Position = "Libero", Age = "Sophomore", Height = "5' 9\"" },
                new Player { PlayerId = 334, PlayerName = "Chloe Kaminski", Number = 25, TeamName = "Oklahoma", Position = "Libero", Age = "Sophomore", Height = "5' 8\"" },

                // West Virginia
                new Player { PlayerId = 335, PlayerName = "Sarah Gooch", Number = 0, TeamName = "West Virginia", Position = "Outside Hitter", Age = "Freshman", Height = "6'1\"" },
                new Player { PlayerId = 336, PlayerName = "Katie Kolar", Number = 1, TeamName = "West Virginia", Position = "Setter", Age = "Freshman", Height = "5'9\"" },
                new Player { PlayerId = 337, PlayerName = "Bailey Miller", Number = 2, TeamName = "West Virginia", Position = "Outside Hitter", Age = "Sophomore", Height = "6'3\"" },
                new Player { PlayerId = 338, PlayerName = "Samiha Foster", Number = 4, TeamName = "West Virginia", Position = "Libero", Age = "Sophomore", Height = "5'9\"" },
                new Player { PlayerId = 339, PlayerName = "Lauren DeLo", Number = 6, TeamName = "West Virginia", Position = "Setter", Age = "Senior", Height = "6'2\"" },
                new Player { PlayerId = 340, PlayerName = "Emma Winter", Number = 7, TeamName = "West Virginia", Position = "Outside Hitter", Age = "Freshman", Height = "6'0\"" },
                new Player { PlayerId = 341, PlayerName = "Tierney Jackson", Number = 8, TeamName = "West Virginia", Position = "Middle Blocker", Age = "Sophomore", Height = "6'4\"" },
                new Player { PlayerId = 342, PlayerName = "Camilla Covas", Number = 9, TeamName = "West Virginia", Position = "Libero", Age = "Graduate", Height = "5'6\"" },
                new Player { PlayerId = 343, PlayerName = "Quincey Coyle", Number = 10, TeamName = "West Virginia", Position = "Outside Hitter", Age = "Sophomore", Height = "6'0\"" },
                new Player { PlayerId = 344, PlayerName = "Melanie McGann", Number = 11, TeamName = "West Virginia", Position = "Opposite Hitter", Age = "Sophomore", Height = "6'3\"" },
                new Player { PlayerId = 345, PlayerName = "Danilyn Neil", Number = 12, TeamName = "West Virginia", Position = "Libero", Age = "Freshman", Height = "5'9\"" },
                new Player { PlayerId = 346, PlayerName = "Emma Beretich", Number = 13, TeamName = "West Virginia", Position = "Middle Blocker", Age = "Freshman", Height = "6'2\"" },
                new Player { PlayerId = 347, PlayerName = "Nele Broszat", Number = 16, TeamName = "West Virginia", Position = "Middle Blocker", Age = "Freshman", Height = "6'2\"" },
                new Player { PlayerId = 348, PlayerName = "Lauren Bodily", Number = 17, TeamName = "West Virginia", Position = "Opposite Hitter", Age = "Sophomore", Height = "6'4\"" },
                new Player { PlayerId = 349, PlayerName = "Hailey Green", Number = 20, TeamName = "West Virginia", Position = "Outside Hitter", Age = "Junior", Height = "6'2\"" },
                new Player { PlayerId = 350, PlayerName = "Kristen McBride", Number = 21, TeamName = "West Virginia", Position = "Libero", Age = "Junior", Height = "5'9\"" },
                new Player { PlayerId = 351, PlayerName = "Maddy McGath", Number = 22, TeamName = "West Virginia", Position = "Middle Blocker", Age = "Freshman", Height = "6'2\"" },


                // Texas Tech
                new Player { PlayerId = 352, PlayerName = "Destiny Cox", Number = 1, TeamName = "Texas Tech", Position = "Outside Hitter", Age = "Graduate", Height = "6' 1\"" },
                new Player { PlayerId = 353, PlayerName = "Abby Dickinson", Number = 2, TeamName = "Texas Tech", Position = "Libero", Age = "Freshman", Height = "5' 8\"" },
                new Player { PlayerId = 354, PlayerName = "Caitlin Dugan", Number = 3, TeamName = "Texas Tech", Position = "Outside Hitter", Age = "Graduate", Height = "6' 1\"" },
                new Player { PlayerId = 355, PlayerName = "Brynn Williams", Number = 4, TeamName = "Texas Tech", Position = "Outside Hitter", Age = "Sophomore", Height = "5' 10\"" },
                new Player { PlayerId = 356, PlayerName = "Madison Gilliland", Number = 5, TeamName = "Texas Tech", Position = "Middle Blocker", Age = "Junior", Height = "6' 2\"" },
                new Player { PlayerId = 357, PlayerName = "Currie Marusak", Number = 6, TeamName = "Texas Tech", Position = "Outside Hitter", Age = "Sophomore", Height = "6' 0\"" },
                new Player { PlayerId = 358, PlayerName = "Paige Mooney", Number = 7, TeamName = "Texas Tech", Position = "Libero", Age = "Sophomore", Height = "5' 8\"" },
                new Player { PlayerId = 359, PlayerName = "Maddie Correa", Number = 9, TeamName = "Texas Tech", Position = "Libero", Age = "Junior", Height = "5' 6\"" },
                new Player { PlayerId = 360, PlayerName = "Katelyn Cochran", Number = 10, TeamName = "Texas Tech", Position = "Setter", Age = "Freshman", Height = "6' 1\"" },
                new Player { PlayerId = 361, PlayerName = "Elena Leontaridou", Number = 11, TeamName = "Texas Tech", Position = "Middle Blocker", Age = "Graduate", Height = "6' 2\"" },
                new Player { PlayerId = 362, PlayerName = "Courtney O'Brien", Number = 12, TeamName = "Texas Tech", Position = "Libero", Age = "Freshman", Height = "5' 11\"" },
                new Player { PlayerId = 363, PlayerName = "Simone Overbeck", Number = 13, TeamName = "Texas Tech", Position = "Outside Hitter", Age = "Graduate", Height = "6' 0\"" },
                new Player { PlayerId = 364, PlayerName = "Claudia Rossi", Number = 14, TeamName = "Texas Tech", Position = "Libero", Age = "Freshman", Height = "5' 8\"" },
                new Player { PlayerId = 365, PlayerName = "Ellie Baumert", Number = 15, TeamName = "Texas Tech", Position = "Setter", Age = "Sophomore", Height = "6' 3\"" },
                new Player { PlayerId = 366, PlayerName = "Reese Rhodes", Number = 16, TeamName = "Texas Tech", Position = "Setter", Age = "Senior", Height = "6' 1\"" },
                new Player { PlayerId = 367, PlayerName = "Reagan Engler", Number = 17, TeamName = "Texas Tech", Position = "Middle Blocker", Age = "Freshman", Height = "6' 1\"" },
                new Player { PlayerId = 368, PlayerName = "Maddie O'Brien", Number = 18, TeamName = "Texas Tech", Position = "Middle Blocker", Age = "Senior", Height = "6' 2\"" },
                new Player { PlayerId = 369, PlayerName = "Kate Hansen", Number = 19, TeamName = "Texas Tech", Position = "Middle Blocker", Age = "Freshman", Height = "6' 3\"" },
                new Player { PlayerId = 370, PlayerName = "Emily Contreras", Number = 21, TeamName = "Texas Tech", Position = "Libero", Age = "Freshman", Height = "5' 5\"" },
                new Player { PlayerId = 371, PlayerName = "Emily Merrick", Number = 23, TeamName = "Texas Tech", Position = "Outside Hitter", Age = "Graduate", Height = "6' 4\"" }
            );

        }
    }
}
